# Generated by Django 4.2.20 on 2025-03-17 08:50

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="customuser",
            options={
                "ordering": ["-date_joined"],
                "permissions": [("can_manage_users", "可以管理普通用户权限")],
                "verbose_name": "用户健康档案",
                "verbose_name_plural": "用户健康档案",
            },
        ),
        migrations.AddField(
            model_name="customuser",
            name="emergency_contact",
            field=models.CharField(
                blank=True,
                help_text="格式：姓名-关系-联系电话（例如：张三-父亲-13800138000）",
                max_length=100,
                validators=[
                    django.core.validators.RegexValidator(
                        message='格式错误。请使用"姓名-关系-手机号"格式，例如：张三-父亲-13800138000',
                        regex="^[\\u4e00-\\u9fa5]{2,10}-[\\u4e00-\\u9fa5]{2,10}-1[3-9]\\d{9}$",
                    )
                ],
                verbose_name="紧急联系人",
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="birth_date",
            field=models.DateField(
                blank=True,
                error_messages={"invalid": "请输入有效的日期格式（YYYY-MM-DD）"},
                help_text="格式：YYYY-MM-DD，用于计算年龄和健康评估",
                null=True,
                verbose_name="出生日期",
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="blood_type",
            field=models.CharField(
                blank=True,
                choices=[("A", "A型"), ("B", "B型"), ("AB", "AB型"), ("O", "O型")],
                default="",
                help_text="请从下拉列表中选择正确的血型分类",
                max_length=5,
                verbose_name="血型",
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="hobbies",
            field=models.TextField(
                blank=True,
                help_text="用逗号分隔多个爱好（例如：游泳, 阅读，最多200字）",
                max_length=200,
                null=True,
                verbose_name="兴趣爱好",
            ),
        ),
        migrations.CreateModel(
            name="FamilyRelationship",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "relation_type",
                    models.CharField(
                        choices=[
                            ("parent", "父母"),
                            ("child", "子女"),
                            ("spouse", "配偶"),
                            ("sibling", "兄弟姐妹"),
                            ("other", "其他关系"),
                        ],
                        help_text="请选择最准确的关系描述",
                        max_length=20,
                        verbose_name="关系类型",
                    ),
                ),
                (
                    "verified",
                    models.BooleanField(
                        default=False,
                        help_text="表示对方是否确认此关系",
                        verbose_name="已验证",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="关系记录的创建时间",
                        verbose_name="建立时间",
                    ),
                ),
                (
                    "from_user",
                    models.ForeignKey(
                        help_text="选择要建立关系的主体用户",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="from_relationships",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用户",
                    ),
                ),
                (
                    "to_user",
                    models.ForeignKey(
                        help_text="选择要关联的家庭成员",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="to_relationships",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="家庭成员",
                    ),
                ),
            ],
            options={
                "verbose_name": "家庭成员关系",
                "verbose_name_plural": "家庭成员关系",
                "ordering": ["-created_at"],
                "unique_together": {("from_user", "to_user", "relation_type")},
            },
        ),
        migrations.AddField(
            model_name="customuser",
            name="family_members",
            field=models.ManyToManyField(
                blank=True,
                help_text="通过下方家庭成员关系表管理关联",
                through="users.FamilyRelationship",
                to=settings.AUTH_USER_MODEL,
                verbose_name="家庭成员",
            ),
        ),
    ]
