# Generated by Django 4.2.20 on 2025-03-22 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='phone',
            field=models.CharField(blank=True, help_text='用户的联系电话，用于紧急联系和找回密码', max_length=20, null=True, verbose_name='手机号码'),
        ),
    ]
